# Generated by Django 5.1.3 on 2026-01-21 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sucursales_a_cargo', to='personal.empleado'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departamentos', to='core.sucursal'),
        ),
        migrations.AddField(
            model_name='turno',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa'),
        ),
        migrations.AlterUniqueTogether(
            name='area',
            unique_together={('empresa', 'nombre')},
        ),
        migrations.AlterUniqueTogether(
            name='puesto',
            unique_together={('empresa', 'nombre')},
        ),
        migrations.AlterUniqueTogether(
            name='departamento',
            unique_together={('sucursal', 'nombre')},
        ),
    ]
