# Generated by Django 5.1.3 on 2026-01-05 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departamento',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='departamento',
            name='padre',
        ),
        migrations.RemoveField(
            model_name='puesto',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='puesto',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='puesto',
            name='nivel',
        ),
        migrations.AddField(
            model_name='puesto',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.area'),
        ),
        migrations.AddField(
            model_name='puesto',
            name='es_supervisor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='radio_metros',
            field=models.IntegerField(default=50, help_text='Radio en metros para permitir marcaje'),
        ),
        migrations.AlterField(
            model_name='area',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='area',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='core.empresa'),
        ),
        migrations.AlterField(
            model_name='puesto',
            name='salario_maximo',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10),
        ),
        migrations.AlterField(
            model_name='puesto',
            name='salario_minimo',
            field=models.DecimalField(decimal_places=2, default=460, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sucursales', to='core.empresa'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
    ]
