# Generated by Django 5.1.3 on 2026-01-13 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('personal', '0002_solicitudausencia_dias_solicitados'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='jefe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departamentos_a_cargo', to='personal.empleado'),
        ),
    ]
