# Generated by Django 5.1.3 on 2026-01-06 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turno',
            name='min_tolerancia',
        ),
        migrations.RemoveField(
            model_name='turno',
            name='minutos_descanso',
        ),
        migrations.AddField(
            model_name='turno',
            name='horas_semanales_meta',
            field=models.IntegerField(default=40, help_text='Ej: 40 horas a la semana'),
        ),
        migrations.AddField(
            model_name='turno',
            name='tipo_jornada',
            field=models.CharField(choices=[('RIGIDO', 'Horario Fijo (Entrada/Salida estricta)'), ('FLEXIBLE', 'Bolsa de Horas (Meta semanal)')], default='RIGIDO', max_length=20),
        ),
        migrations.AlterField(
            model_name='turno',
            name='dias_laborables',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='turno',
            name='hora_entrada',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='turno',
            name='hora_salida',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
