# Generated by Django 5.1.3 on 2026-01-20 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='departamento',
            unique_together={('sucursal', 'nombre')},
        ),
        migrations.AlterUniqueTogether(
            name='puesto',
            unique_together={('empresa', 'nombre')},
        ),
    ]
