# Generated by Django 5.2.8 on 2026-01-21 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionNomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moneda', models.CharField(default='USD', help_text='Ej: USD, EUR, MXN', max_length=5)),
                ('divisor_hora_mensual', models.IntegerField(default=240, help_text='Divisor para calcular valor hora. Ej: 240 (30 días * 8h) o 160 (20 días * 8h)')),
                ('factor_he_diurna', models.DecimalField(decimal_places=2, default=1.5, max_digits=4)),
                ('factor_he_nocturna', models.DecimalField(decimal_places=2, default=2.0, max_digits=4)),
                ('hora_inicio_nocturna', models.TimeField(default='19:00:00')),
                ('descontar_atrasos', models.BooleanField(default=True, help_text='Si es True, se resta del sueldo el tiempo de atraso.')),
                ('tolerancia_remunerada', models.BooleanField(default=True, help_text='Si llega tarde dentro de la tolerancia, ¿se le paga ese tiempo?')),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_nomina', to='core.empresa')),
            ],
        ),
    ]
