# Generated by Django 5.1.3 on 2026-01-13 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_departamento_jefe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puesto',
            name='salario_maximo',
        ),
        migrations.RemoveField(
            model_name='puesto',
            name='salario_minimo',
        ),
    ]
