# Generated by Django 5.1.3 on 2026-01-06 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_turno_min_tolerancia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='min_tolerancia',
            field=models.IntegerField(default=10, help_text='Minutos de gracia antes de marcar atraso'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='horas_semanales_meta',
            field=models.IntegerField(default=40, help_text='Total de horas a cumplir (Ej: 40)'),
        ),
    ]
