# Generated by Django 5.1.3 on 2026-01-13 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_puesto_salario_maximo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departamento',
            name='jefe',
        ),
    ]
