# Generated by Django 5.2.8 on 2026-01-14 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CHECK_IN', 'Entrada'), ('CHECK_OUT', 'Salida')], max_length=20)),
                ('registrado_el', models.DateTimeField()),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('foto_evidencia', models.ImageField(blank=True, null=True, upload_to='asistencia_evidencia/')),
                ('observacion', models.CharField(blank=True, max_length=200)),
                ('fuente', models.CharField(default='APP', max_length=50)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.empleado')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Jornada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_entrada_real', models.TimeField(null=True)),
                ('hora_salida_real', models.TimeField(null=True)),
                ('minutos_trabajados', models.IntegerField(default=0)),
                ('minutos_atraso', models.IntegerField(default=0)),
                ('minutos_extras', models.IntegerField(default=0)),
                ('es_ausencia', models.BooleanField(default=False)),
                ('es_vacacion', models.BooleanField(default=False)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.empleado')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
            ],
            options={
                'unique_together': {('empleado', 'fecha')},
            },
        ),
    ]
