# Generated by Django 5.2.8 on 2026-01-23 08:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventoAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida')], max_length=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('latitud', models.DecimalField(decimal_places=7, max_digits=10, null=True)),
                ('longitud', models.DecimalField(decimal_places=7, max_digits=10, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='evidencia_asistencia/%Y/%m/')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device_info', models.CharField(blank=True, help_text='User Agent o ID del App', max_length=255)),
                ('exitoso', models.BooleanField(default=True)),
                ('error_motivo', models.CharField(blank=True, help_text='Ej: Fuera de rango', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Jornada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(help_text='Fecha contable de la jornada (independiente de si cruza medianoche)')),
                ('entrada', models.DateTimeField(blank=True, null=True)),
                ('salida', models.DateTimeField(blank=True, null=True)),
                ('horas_trabajadas', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('horas_extras', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('minutos_atraso', models.IntegerField(default=0)),
                ('es_atraso', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('ABIERTA', 'En curso'), ('CERRADA', 'Finalizada'), ('AUSENTE', 'Ausencia Injustificada'), ('JUSTIFICADA', 'Falta Justificada/Permiso'), ('ERROR', 'Error de Marcaje (Sin salida)')], default='ABIERTA', max_length=20)),
                ('es_manual', models.BooleanField(default=False, help_text='¿Fue creado/editado manualmente por un supervisor?')),
                ('observacion', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
