# Generated by Django 5.2.8 on 2026-01-21 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asistencia', '0001_initial'),
        ('core', '0001_initial'),
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoasistencia',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_asistencia', to='personal.empleado'),
        ),
        migrations.AddField(
            model_name='eventoasistencia',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa'),
        ),
        migrations.AddField(
            model_name='jornada',
            name='editado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jornadas_editadas', to='personal.empleado'),
        ),
        migrations.AddField(
            model_name='jornada',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jornadas', to='personal.empleado'),
        ),
        migrations.AddField(
            model_name='jornada',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa'),
        ),
        migrations.AddIndex(
            model_name='eventoasistencia',
            index=models.Index(fields=['empleado', 'timestamp'], name='asistencia__emplead_69ee6b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='jornada',
            unique_together={('empleado', 'fecha')},
        ),
    ]
