# Generated by Django 5.2.8 on 2026-01-23 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=150)),
                ('apellidos', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=100)),
                ('direccion', models.TextField(blank=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='empleados/', verbose_name='Foto de Perfil')),
                ('documento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cédula/DNI')),
                ('rol', models.CharField(choices=[('SUPERADMIN', 'Super Admin (SaaS)'), ('ADMIN', 'Cliente / Dueño'), ('RRHH', 'Recursos Humanos'), ('GERENTE', 'Gerente de Sucursal'), ('EMPLEADO', 'Colaborador')], default='EMPLEADO', max_length=100)),
                ('fecha_ingreso', models.DateField()),
                ('sueldo', models.DecimalField(decimal_places=2, default=460, max_digits=10)),
                ('es_mensualizado', models.BooleanField(default=True, help_text='True=Pago Mensual, False=Pago por Hora')),
                ('saldo_vacaciones', models.IntegerField(default=15)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=100)),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleados', to='core.departamento')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empleados', to='core.empresa')),
                ('puesto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.puesto')),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sucursal')),
                ('turno_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.turno', verbose_name='Turno Fijo')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empleado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('empresa', 'documento'), ('empresa', 'email')},
            },
        ),
        migrations.CreateModel(
            name='DocumentoEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CONTRATO', 'Contrato Firmado'), ('CEDULA', 'Cédula'), ('TITULO', 'Título'), ('OTRO', 'Otro')], max_length=20)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='documentos_empleados/')),
                ('observacion', models.TextField(blank=True)),
                ('cargado_el', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INDEFINIDO', 'Indefinido'), ('PLAZO_FIJO', 'Plazo Fijo'), ('PASANTIA', 'Pasantía')], default='INDEFINIDO', max_length=50)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('salario_mensual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='contratos/')),
                ('activo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='personal.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_limite', models.DateTimeField(blank=True, null=True)),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente 🔥')], default='MEDIA', max_length=10)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Por Hacer'), ('PROGRESO', 'En Curso'), ('REVISION', 'En Revisión'), ('COMPLETADA', 'Completada ✅')], default='PENDIENTE', max_length=15)),
                ('puntos_valor', models.IntegerField(default=1, help_text='Puntos que gana el empleado al completar (1-10)')),
                ('motivo_rechazo', models.TextField(blank=True, help_text='Razón por la que fue rechazada', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completado_at', models.DateTimeField(blank=True, null=True)),
                ('asignado_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas_asignadas', to='personal.empleado')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_creadas', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_revisadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TipoAusencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('afecta_sueldo', models.BooleanField(default=False)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudAusencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_solicitados', models.IntegerField(default=0)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('motivo', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=20)),
                ('fecha_resolucion', models.DateField(blank=True, null=True)),
                ('motivo_rechazo', models.TextField(blank=True)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ausencias_aprobadas', to='personal.empleado')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.empleado')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
                ('tipo_ausencia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='personal.tipoausencia')),
            ],
        ),
    ]
