# Generated by Django 5.1.3 on 2026-01-12 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudausencia',
            name='dias_solicitados',
            field=models.IntegerField(default=0),
        ),
    ]
