# Generated by Django 5.2.8 on 2026-01-21 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_configuracionnomina'),
        ('personal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='es_mensualizado',
            field=models.BooleanField(default=True, help_text='True=Pago Mensual, False=Pago por Hora'),
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_limite', models.DateTimeField(blank=True, null=True)),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente 🔥')], default='MEDIA', max_length=10)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Por Hacer'), ('PROGRESO', 'En Curso'), ('REVISION', 'En Revisión'), ('COMPLETADA', 'Completada ✅')], default='PENDIENTE', max_length=15)),
                ('puntos_valor', models.IntegerField(default=1, help_text='Puntos que gana el empleado al completar (1-10)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completado_at', models.DateTimeField(blank=True, null=True)),
                ('asignado_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas_asignadas', to='personal.empleado')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_creadas', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
            ],
        ),
    ]
