# Generated by Django 5.1.3 on 2026-01-20 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_departamento_unique_together_and_more'),
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterUniqueTogether(
            name='empleado',
            unique_together={('empresa', 'documento'), ('empresa', 'email')},
        ),
    ]
