# Generated by Django 5.1.3 on 2026-01-06 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudausencia',
            name='motivo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
