# Generated by Django 5.1.3 on 2026-01-13 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_departamento_jefe'),
        ('personal', '0002_solicitudausencia_dias_solicitados'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='personal.empleado'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleados', to='core.departamento'),
        ),
    ]
