# Generated by Django 5.2.8 on 2026-01-21 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_empleado_es_mensualizado_tarea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='empleados/', verbose_name='Foto de Perfil'),
        ),
    ]
