# Generated by Django 5.2.8 on 2026-01-22 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_alter_empleado_foto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='motivo_rechazo',
            field=models.TextField(blank=True, help_text='Razón por la que fue rechazada', null=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='revisado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_revisadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
