# Generated by Django 5.1.3 on 2025-12-16 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('unidad', models.CharField(choices=[('PORCENTAJE', '%'), ('PUNTOS', 'Puntos')], max_length=20)),
                ('meta_objetivo', models.DecimalField(decimal_places=2, max_digits=5)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=20)),
                ('valor_obtenido', models.DecimalField(decimal_places=2, max_digits=5)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.empleado')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kpi.kpi')),
            ],
        ),
    ]
