# Generated by Django 5.2.8 on 2026-01-23 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluacionDesempeno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_evaluacion', models.DateField(auto_now_add=True)),
                ('periodo', models.CharField(max_length=20)),
                ('puntaje_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('estado', models.CharField(default='BORRADOR', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.empleado')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('categoria', models.CharField(choices=[('ASISTENCIA', 'Puntualidad y Asistencia'), ('DESEMPENO', 'Desempeño y Objetivos'), ('COMPETENCIA', 'Competencias y Títulos'), ('OTRO', 'Otro')], default='DESEMPENO', max_length=20)),
                ('peso_porcentaje', models.IntegerField(default=0, help_text='Peso de este KPI en la nota final (0-100)')),
                ('meta_objetivo', models.DecimalField(decimal_places=2, default=100.0, max_digits=10)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_obtenido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('calificacion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('comentario', models.CharField(blank=True, max_length=200)),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='kpi.evaluaciondesempeno')),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kpi.kpi')),
            ],
        ),
        migrations.CreateModel(
            name='Objetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('meta_numerica', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('avance_actual', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('fecha_limite', models.DateField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROGRESO', 'En Progreso'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20)),
                ('prioridad', models.CharField(choices=[('ALTA', 'Alta'), ('MEDIA', 'Media'), ('BAJA', 'Baja')], default='MEDIA', max_length=10)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetivos', to='personal.empleado')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
            ],
        ),
    ]
