# Generated by Django 5.2.8 on 2026-01-03 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kpi',
            name='meta_objetivo',
        ),
        migrations.AddField(
            model_name='kpi',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kpi',
            name='meta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resultadokpi',
            name='fecha_evaluacion',
            field=models.DateTimeField(auto_now_add=True, default='2025-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kpi',
            name='unidad',
            field=models.CharField(choices=[('%', 'Porcentaje (%)'), ('USD', 'Moneda ($)'), ('NUM', 'Cantidad (#)'), ('PTS', 'Puntos (1-10)')], default='%', max_length=5),
        ),
        migrations.AlterField(
            model_name='resultadokpi',
            name='periodo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='resultadokpi',
            name='valor_obtenido',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
